extends:
  - airbnb-typescript
env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  'import/no-cycle': off
  no-console: warn
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-param-reassign: off
