extends:
  - airbnb-typescript
env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  # no-console: off
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  import/no-cycle:
    - off
  no-param-reassign: off
